import { useEffect, useState } from "react";
import { supabase, isSupabaseConfigured } from "../lib/supabase";
const label = { pending_payment: "Pending payment", approved: "Confirmed", processing: "Processing", completed: "Completed", cancelled: "Cancelled" };
export default function CustomerOrders({ session, go }) {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true);
  const load = async () => { if (!supabase || !session) { setLoading(false); return; } setLoading(true); const { data } = await supabase.from("orders").select("*, order_items(*)").order("created_at", { ascending: false }); setOrders(data || []); setLoading(false); };
  useEffect(() => { load(); }, [session]);
  if (!session) return <main className="page-shell simple-page"><p className="eyebrow">MY ACCOUNT</p><h1>Sign in for your <em>orders.</em></h1><p>Create or use your customer account to track pending, confirmed and completed orders.</p><button className="button button-ink" onClick={() => go("/login")}>Sign in to my account</button></main>;
  if (!isSupabaseConfigured) return <main className="page-shell simple-page"><h1>Your <em>orders.</em></h1><p>Connect Supabase to load your order history.</p></main>;
  return <main className="page-shell simple-page"><div className="orders-heading"><div><p className="eyebrow">MY ACCOUNT</p><h1>Your <em>orders.</em></h1></div><button className="text-link" onClick={load}>Refresh status</button></div>{loading ? <p>Loading your orders…</p> : orders.length ? <div className="order-list">{orders.map((order) => <article key={order.id}><div><span className={"order-status " + order.status}>{label[order.status] || order.status.replaceAll("_", " ")}</span><strong>#{order.id.slice(0, 8)}</strong><small>{new Date(order.created_at).toLocaleDateString()}</small></div><p>{order.order_items?.map((item) => item.product_name + " × " + item.quantity).join(", ")}</p><b>PKR {Number(order.total).toLocaleString()}</b>{order.status === "pending_payment" && <em>Send your advance-payment screenshot on WhatsApp. Your order will change to Confirmed after approval.</em>}{order.status === "approved" && <em>Your payment has been confirmed. We are preparing your order.</em>}</article>)}</div> : <div className="orders-empty"><h3>No orders yet</h3><p>When you place an order, its pending-payment status will appear here.</p><button className="button button-ink" onClick={() => go("/shop")}>Start shopping</button></div>}</main>;
}
