import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import "./PaymentSettingsAdmin.css";
const initial={easypaisa_number:"03234724373",easypaisa_name:"Muhammad Usama",jazzcash_number:"03234724373",jazzcash_name:"Muhammad Usama",bank_name:"HBL",bank_account:"06147900940851",bank_account_name:"Muhammad Usama"};
const replaceLegacyDetails=(data={})=>({...initial,...data,easypaisa_number:data.easypaisa_number==="03317047951"?initial.easypaisa_number:(data.easypaisa_number||initial.easypaisa_number),easypaisa_name:data.easypaisa_name==="Muhammad Hamdan Amir"?initial.easypaisa_name:(data.easypaisa_name||initial.easypaisa_name),jazzcash_number:data.jazzcash_number==="03317047951"?initial.jazzcash_number:(data.jazzcash_number||initial.jazzcash_number),jazzcash_name:data.jazzcash_name==="Muhammad Hamdan Amir"?initial.jazzcash_name:(data.jazzcash_name||initial.jazzcash_name),bank_name:data.bank_name==="Meezan Bank"?initial.bank_name:(data.bank_name||initial.bank_name),bank_account:data.bank_account==="00300115864047"?initial.bank_account:(data.bank_account||initial.bank_account),bank_account_name:data.bank_account_name==="Muhammad Hamdan Amir"?initial.bank_account_name:(data.bank_account_name||initial.bank_account_name)});
export default function PaymentSettingsAdmin({ notice }) {
 const [form,setForm]=useState(initial);
 useEffect(()=>{supabase.from("store_settings").select("*").eq("id",true).single().then(({data})=>data&&setForm(replaceLegacyDetails(data)))},[]);
 const save=async e=>{e.preventDefault();const {error}=await supabase.from("store_settings").update({...form,id:true,updated_at:new Date().toISOString()}).eq("id",true);notice(error?.message||"Payment settings saved.");};
 return <form className="admin-product-form payment-settings" onSubmit={save}><div className="payment-settings-head"><div><h2>Advance payment details</h2><p>Customers see these exact account titles and numbers at checkout.</p></div><span>LIVE STORE SETTINGS</span></div><section className="payment-method-group"><header><strong>EasyPaisa</strong><small>Mobile wallet</small></header><label className="admin-field"><span>EasyPaisa account number</span><input required placeholder="e.g. 03234724373" value={form.easypaisa_number} onChange={e=>setForm({...form,easypaisa_number:e.target.value})}/></label><label className="admin-field"><span>EasyPaisa account title / name</span><input required placeholder="e.g. Muhammad Usama" value={form.easypaisa_name} onChange={e=>setForm({...form,easypaisa_name:e.target.value})}/></label></section><section className="payment-method-group"><header><strong>SadaPay</strong><small>Mobile wallet</small></header><label className="admin-field"><span>SadaPay account number</span><input required placeholder="e.g. 03234724373" value={form.jazzcash_number} onChange={e=>setForm({...form,jazzcash_number:e.target.value})}/></label><label className="admin-field"><span>SadaPay account title / name</span><input required placeholder="e.g. Muhammad Usama" value={form.jazzcash_name} onChange={e=>setForm({...form,jazzcash_name:e.target.value})}/></label></section><section className="payment-method-group bank-payment-group"><header><strong>HBL bank transfer</strong><small>Account transfer</small></header><label className="admin-field"><span>Bank name</span><input required placeholder="e.g. HBL" value={form.bank_name} onChange={e=>setForm({...form,bank_name:e.target.value})}/></label><label className="admin-field"><span>Account / IBAN number</span><input required placeholder="e.g. 06147900940851" value={form.bank_account} onChange={e=>setForm({...form,bank_account:e.target.value})}/></label><label className="admin-field full"><span>Bank account title / holder name</span><input required placeholder="e.g. Muhammad Usama" value={form.bank_account_name} onChange={e=>setForm({...form,bank_account_name:e.target.value})}/></label></section><button className="button button-ink">Save all payment details</button></form>;
}
