const isUuid = (val) => typeof val === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(val);
import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useMemo, useRef, useState } from "react";
import easypaisaLogo from "./assets/easypaisa.png";
import jazzcashLogo from "./assets/jazzcash.png";
import techoraLogo from "./assets/techora-logo.png";
import "./App.css";
import "./reference-theme.css";
import { supabase } from "./lib/supabase";
import AuthScreen from "./components/AuthScreen";
import CustomerOrders from "./components/CustomerOrders";
import LiveReviews from "./components/LiveReviews";
import AdminDashboard from "./components/AdminDashboard";
import HeroCarousel from "./components/HeroCarousel";
import PaymentInstructions from "./components/PaymentInstructions";
import ProductMarquee from "./components/ProductMarquee";
import { fallbackProducts } from "./data/catalog";

const money = (number) => `PKR ${Number(number || 0).toLocaleString()}`;
const originalPrice = (product) => { const discount = Number(product.discount || 0); return discount > 0 ? Math.round(Number(product.price) / (1 - discount / 100)) : Number(product.price); };

function Icon({ name }) {
  const paths = { menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>, close:<path d="M6 6l12 12M18 6 6 18"/>, search:<><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></>, heart:<path d="M20.8 8.6c0 5.2-8.8 10.4-8.8 10.4S3.2 13.8 3.2 8.6A4.4 4.4 0 0 1 11 5.8L12 7l1-1.2a4.4 4.4 0 0 1 7.8 2.8Z"/>, bag:<><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>, arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>, plus:<><path d="M12 5v14M5 12h14"/></>, sliders:<><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="2"/><circle cx="15" cy="17" r="2"/></>, user:<><circle cx="12" cy="8" r="3.3"/><path d="M5.5 20c.55-3.4 3.1-5.35 6.5-5.35S17.95 16.6 18.5 20"/></>, whatsapp:<path d="M12 3a8.7 8.7 0 0 0-7.5 13.1L3.4 21l5-1.3A8.7 8.7 0 1 0 12 3Zm0 15.9c-1.3 0-2.6-.35-3.7-1l-.27-.16-2.96.78.8-2.88-.18-.3A7.16 7.16 0 1 1 12 18.9Zm3.94-5.37c-.22-.11-1.3-.64-1.5-.71-.2-.07-.35-.11-.5.11-.15.22-.56.7-.69.84-.13.15-.26.17-.48.06-.22-.11-.92-.34-1.75-1.08-.65-.57-1.08-1.28-1.21-1.5-.13-.22-.02-.34.1-.45.1-.1.22-.25.32-.38.11-.13.14-.22.22-.36.07-.15.04-.28-.02-.39-.06-.11-.5-1.2-.68-1.64-.18-.43-.36-.37-.5-.38h-.43c-.15 0-.39.06-.59.28-.2.22-.77.75-.77 1.83s.79 2.12.9 2.27c.11.15 1.55 2.37 3.75 3.33.52.23.94.36 1.26.47.53.17 1.02.14 1.4.09.43-.06 1.3-.53 1.48-1.04.19-.51.19-.95.13-1.04-.05-.09-.2-.15-.42-.26Z"/> };
  return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>;
}

export default function App() {
  const [session, setSession] = useState(null);
  const [products, setProducts] = useState(fallbackProducts);
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession)); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!supabase) return; const loadProducts = () => supabase.from("products").select("*").eq("is_active", true).order("created_at", { ascending: false }).then(({ data }) => { if (data?.length) setProducts(data.map(item => ({ ...item, image: item.image_url, gallery: Array.isArray(item.gallery) ? item.gallery : [], colors: Array.isArray(item.colors) ? item.colors : [], price: Number(item.price) * (1 - Number(item.discount || 0) / 100) }))); }); loadProducts(); const timer = window.setInterval(loadProducts, 15000); return () => window.clearInterval(timer); }, []);
  const [path, setPath] = useState(window.location.pathname);
  const [cart, setCart] = useState([]);
  const [wishlist, setWishlist] = useState([]);
  const [menuOpen, setMenuOpen] = useState(false);
  const [toast, setToast] = useState("");
  const [filter, setFilter] = useState("All");
  const [limit, setLimit] = useState(10000);
  const [sort, setSort] = useState("Featured");
  const cartRef = useRef(null);
  const [flying, setFlying] = useState(null);
  useEffect(() => { const onPop = () => setPath(window.location.pathname); addEventListener("popstate", onPop); return () => removeEventListener("popstate", onPop); }, []);
  const go = (url) => { if (url !== window.location.pathname) { window.history.pushState({}, "", url); setPath(url); window.scrollTo({ top: 0, behavior: "smooth" }); } setMenuOpen(false); };
  const notice = (text) => { setToast(text); window.setTimeout(() => setToast(""), 2300); };
  const add = (product, event) => { const cartKey = `${product.id}::${product.selectedColor || "default"}`; const item = { ...product, cartKey }; const a = event?.currentTarget?.getBoundingClientRect(), b = cartRef.current?.getBoundingClientRect(); if (a && b && !matchMedia("(prefers-reduced-motion: reduce)").matches) setFlying({ product: item, x:a.left+a.width/2-24, y:a.top+a.height/2-24, dx:b.left+b.width/2-(a.left+a.width/2), dy:b.top+b.height/2-(a.top+a.height/2) }); setCart(old => old.some(entry => entry.cartKey === cartKey) ? old : [...old, item]); notice(`${product.name} added to your bag.`); };
  const toggleWish = (product) => setWishlist(old => old.includes(product.id) ? old.filter(id => id !== product.id) : [...old, product.id]);
  const openProduct = (product) => go(`/product/${product.id}`);
  const selected = products.find(product => `/product/${product.id}` === path) || fallbackProducts.find(product => `/product/${product.id}` === path);
  const filtered = useMemo(() => products.filter(product => (filter === "All" || product.category === filter) && product.price <= limit).sort((a,b) => sort === "Price: low to high" ? a.price-b.price : sort === "Price: high to low" ? b.price-a.price : a.id-b.id), [filter, limit, sort]);
  const isAdminRoute = path === "/admin" || path === "/admin-login";
  if (isAdminRoute) return session ? <AdminDashboard session={session} go={go}/> : <AuthScreen go={go} mode="admin"/>;
  const nav = [["Home", "/"], ["Shop", "/shop"], ["Categories", "/shop"], ["New arrivals", "/shop"], ["Best sellers", "/shop"]];
  return <div className="site-shell">
    <div className="topline" aria-label="Free shipping on orders over PKR 5,000"><div className="shipping-marquee"><div className="shipping-marquee-track"><span>Free shipping on orders over PKR 5,000</span><span aria-hidden="true">Free shipping on orders over PKR 5,000</span></div></div></div>
    <header className="nav-wrap"><button className="mobile-menu-button mobile-only" onClick={() => setMenuOpen(true)} aria-label="Open menu"><Icon name="menu"/></button><button className="mobile-account-button mobile-only" onClick={() => go(session ? "/orders" : "/login")} aria-label={session ? "Open my orders" : "Sign in"}><Icon name="user"/></button><button className="wordmark" onClick={() => go("/")} aria-label="Techora home"><img src={techoraLogo} alt="Techora Gadgets"/></button><nav className="desktop-nav">{nav.map(([label,url]) => <button key={label} onClick={() => go(url)} className={path === url || (url === "/shop" && path.startsWith("/product/")) ? "nav-active" : ""}>{label}</button>)}</nav><div className="nav-tools"><button className="icon-button desktop-search" aria-label="Search"><Icon name="search"/></button><button className="icon-button" onClick={() => go("/wishlist")} aria-label="Wishlist"><Icon name="heart"/><b>{wishlist.length}</b></button><button ref={cartRef} className="icon-button" onClick={() => go("/cart")} aria-label="Shopping bag"><Icon name="bag"/><b>{cart.length}</b></button></div></header>
    <AnimatePresence>{menuOpen && <motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="mobile-menu-panel" initial={{x:-28}} animate={{x:0}} exit={{x:-28}}><button className="icon-button menu-close" onClick={() => setMenuOpen(false)}><Icon name="close"/></button>{nav.map(([label,url]) => <button key={label} onClick={() => go(url)}>{label}</button>)}<button onClick={() => go("/orders")}>My orders</button></motion.div></motion.div>}</AnimatePresence>
    {path === "/" && <Home go={go} openProduct={openProduct} products={products} add={add} wish={wishlist} toggleWish={toggleWish} session={session}/>} {path === "/shop" && <Shop products={filtered} filter={filter} setFilter={setFilter} limit={limit} setLimit={setLimit} sort={sort} setSort={setSort} openProduct={openProduct} add={add} wish={wishlist} toggleWish={toggleWish}/>} {selected && <Product product={selected} add={add} wished={wishlist.includes(selected.id)} toggleWish={toggleWish} go={go} session={session}/>} {path === "/cart" && <Cart cart={cart} go={go} session={session} clearCart={()=>setCart([])}/>} {path === "/wishlist" && <SimpleList title="Your wishlist" products={products.filter(p=>wishlist.includes(p.id))} openProduct={openProduct}/>} {path === "/orders" && <CustomerOrders session={session} go={go}/>} {path === "/reviews" && <LiveReviews session={session} go={go}/>} {path === "/login" && <AuthScreen go={go} mode="customer"/>} {path === "/story" && <Story go={go}/>}
    <Footer go={go}/><a className="floating-whatsapp" href="https://wa.me/923229701332?text=Hi%20Techora%2C%20I%20need%20help%20with%20a%20product." target="_blank" rel="noreferrer" aria-label="Chat with Techora on WhatsApp"><Icon name="whatsapp"/></a>
    <AnimatePresence>{flying && <motion.img className="fly-to-cart" src={flying.product.image} alt="" initial={{opacity:1,scale:1,x:0,y:0}} animate={{opacity:.15,scale:.2,x:flying.dx,y:flying.dy}} transition={{duration:.55}} style={{left:flying.x,top:flying.y}} onAnimationComplete={() => setFlying(null)}/>}</AnimatePresence><AnimatePresence>{toast && <motion.div className="toast" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}}>{toast}</motion.div>}</AnimatePresence>
  </div>;
}
function Home({go,openProduct,products,add,wish,toggleWish,session}) {
  const categories=products.map(product => [product.category, product.name, product.image]);
  const best=products.slice(0,4), fresh=products.slice(4,8);
  return <main><HeroCarousel go={go}/>
    <section className="home-trustbar" aria-label="Why shop with Techora">{[["⚡","Fast dispatch","Across Pakistan"],["✓","Quality checked","Before it ships"],["🔒","Secure payment","Multiple options"],["◌","WhatsApp support","Here to help"]].map(([icon,title,copy])=><div key={title}><b>{icon}</b><span><strong>{title}</strong><small>{copy}</small></span></div>)}</section>
    <ProductMarquee products={products} openProduct={openProduct}/>
    <section className="section premium-categories"><div className="shop-heading"><div><p className="eyebrow">SHOP BY CATEGORY</p><h2>Find your next <em>upgrade.</em></h2></div><button className="text-link" onClick={()=>go("/shop")}>See all products <Icon name="arrow"/></button></div><div className="premium-category-grid">{categories.map(([name,copy,image])=><button key={name} onClick={()=>go("/shop")}><img src={image} alt=""/><span/><div><p>{copy}</p><h3>{name}</h3><em>Explore <Icon name="arrow"/></em></div></button>)}</div></section>
    <ProductShelf eyebrow="BEST SELLERS" title={<>The Techora <em>favourites.</em></>} products={best} go={go} openProduct={openProduct} add={add} wish={wish} toggleWish={toggleWish}/>
    <section className="deal-banner"><div><p className="eyebrow">LIMITED-TIME SAVINGS</p><h2>Today&apos;s <em>Tech Deals.</em></h2><p>Premium upgrades with prices worth acting on. New offers arrive regularly.</p><button className="button button-ink" onClick={()=>go("/shop")}>Shop special offers <Icon name="arrow"/></button></div><div className="deal-stat"><strong>UP TO<br/><em>20%</em></strong><span>OFF SELECTED TECH</span></div></section>
    <ProductShelf eyebrow="NEW ARRIVALS" title={<>Fresh tech, <em>just in.</em></>} products={fresh} go={go} openProduct={openProduct} add={add} wish={wish} toggleWish={toggleWish}/>
    <section className="section service-section"><div className="section-intro"><p className="eyebrow">WHY SHOP WITH TECHORA</p><h2>Technology backed by <em>real support.</em></h2></div><div className="service-grid">{[["Nationwide delivery","Fast, careful delivery to cities across Pakistan."],["Secure payments","EasyPaisa, JazzCash and bank transfer options."],["Quality products","Useful tech selected for genuine everyday value."],["Easy help","Quick assistance on WhatsApp before and after your order."]].map(([t,c])=><div className="service-card" key={t}><h3>{t}</h3><p>{c}</p></div>)}</div></section>
    <LiveReviews session={session} go={go} embedded/>
  </main>
}
function ProductShelf({eyebrow,title,products,go,openProduct,add,wish,toggleWish}) { return <section className="section home-products"><div className="shop-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button className="text-link" onClick={() => go("/shop")}>View all <Icon name="arrow"/></button></div><div className="products-grid">{products.map((p,i)=><ProductCard key={p.id} product={p} index={i} openProduct={openProduct} add={add} wished={wish.includes(p.id)} toggleWish={toggleWish}/>)}</div></section> }function Shop({products,filter,setFilter,limit,setLimit,sort,setSort,openProduct,add,wish,toggleWish}) { const cats=["All","Audio","Wearables","Accessories","Gaming","New arrivals"]; return <main className="page-shell"><div className="breadcrumb">Home <span>/</span> Shop</div><div className="page-heading"><div><p className="eyebrow">SHOP TECHORA</p><h1>The complete <em>edit.</em></h1></div><p>Devices and accessories selected for everyday life.</p></div><div className="shop-layout"><aside className="shop-sidebar"><div className="filter-title"><Icon name="sliders"/> Filters</div><p className="filter-label">Category</p>{cats.map(cat=><button className={filter===cat?"active":""} onClick={()=>setFilter(cat)} key={cat}>{cat}</button>)}<p className="filter-label range-label">Price range <strong>{money(limit)}</strong></p><input type="range" min="3000" max="10000" step="500" value={limit} onChange={e=>setLimit(Number(e.target.value))}/></aside><section className="shop-results"><div className="results-top"><span>{products.length} products</span><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Price: low to high</option><option>Price: high to low</option></select></label></div><div className="products-grid">{products.map((p,i)=><ProductCard key={p.id} product={p} index={i} openProduct={openProduct} add={add} wished={wish.includes(p.id)} toggleWish={toggleWish}/>)}</div></section></div></main> }
function ProductCard({product,index,openProduct,add,wished,toggleWish}) {
  const discount=Number(product.discount||0); const badge=product.stock===0?"SOLD OUT":discount>0?`${discount}% OFF`:index<2?"BEST SELLER":"NEW";
  return <motion.article className="product-card clickable-card" initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.04}}><button className="product-image" onClick={()=>openProduct(product)} aria-label={`View ${product.name}`}><img src={product.image} alt={product.name}/><span className="product-badge">{badge}</span>{product.stock===0&&<span className="unavailable">Product unavailable</span>}</button><button className={wished?"wish active":"wish"} onClick={()=>toggleWish(product)} aria-label="Add to wishlist"><Icon name="heart"/></button><div className="product-info"><p>{product.category}</p><button className="product-name" onClick={()=>openProduct(product)}>{product.name}</button><div className="product-rating-row"><span className="rating-stars" aria-label="Product rating">{Number(product.rating)>0 ? "★".repeat(Math.round(Number(product.rating))) + "☆".repeat(5-Math.round(Number(product.rating))) : "☆☆☆☆☆"}</span><small>{Number(product.rating)>0 ? `${product.rating}/5` : "Not yet rated"}</small></div><div>{discount > 0 ? <span className="discount-price"><del>{money(originalPrice(product))}</del><strong>{money(product.price)}</strong><em>{discount}% off</em></span> : <strong>{money(product.price)}</strong>}<button disabled={product.stock===0} onClick={e=>add(product,e)} aria-label="Add to bag"><Icon name="bag"/></button></div></div></motion.article>;
}
function Product({product,add,wished,toggleWish,go,session}) {
  const gallery = [...new Set([product.image, ...(product.gallery || [])].filter(Boolean))];
  const colors = Array.isArray(product.colors) ? product.colors : [];
  const [currentImage, setCurrentImage] = useState(gallery[0]);
  const [selectedColor, setSelectedColor] = useState(colors[0]?.name || "");
  const [ordering, setOrdering] = useState(false);
  useEffect(() => {
    setCurrentImage(gallery[0]);
    setSelectedColor(colors[0]?.name || "");
  }, [product.id]);
  const configuredProduct = { ...product, selectedColor };
  const chooseColor = (color) => {
    setSelectedColor(color.name);
    if (color.image) setCurrentImage(color.image);
  };
  return <main className="page-shell product-page">
    <div className="breadcrumb"><button onClick={()=>go("/shop")}>Shop</button> <span>/</span> {product.name}</div>
    <div className="product-detail-page">
      <div className="product-gallery">
        <div className="product-detail-image"><AnimatePresence mode="wait"><motion.img key={currentImage} src={currentImage} alt={product.name + (selectedColor ? " in " + selectedColor : "")} initial={{opacity:.25}} animate={{opacity:1}} exit={{opacity:.2}} transition={{duration:.2}}/></AnimatePresence></div>
        {gallery.length > 1 && <div className="product-thumbnails" aria-label="Product images">{gallery.map((image,index)=><button className={currentImage===image?"active":""} key={image} onClick={()=>setCurrentImage(image)} aria-label={"View image " + (index+1)}><img src={image} alt=""/></button>)}</div>}
      </div>
      <div className="product-detail-copy">
        <p className="eyebrow">{product.category}</p><h1>{product.name}</h1>
        <div className="detail-price">{Number(product.discount || 0) > 0 && <del>{money(originalPrice(product))}</del>}<strong>{money(product.price)}</strong>{Number(product.discount || 0) > 0 && <span>{product.discount}% off</span>}</div>
        <p>{product.description}</p>
        {colors.length > 0 && <fieldset className="colour-picker"><legend>Choose colour <strong>{selectedColor}</strong></legend><div>{colors.map(color=><button type="button" key={color.name} className={selectedColor===color.name?"active":""} onClick={()=>chooseColor(color)} aria-label={"Choose " + color.name} aria-pressed={selectedColor===color.name}><span style={{backgroundColor:color.hex || "#ddd"}}/><small>{color.name}</small></button>)}</div></fieldset>}
        <p className={product.stock===0?"stock-state sold-out":"stock-state"}>{product.stock===0?"Unavailable":"In stock — ready to order"}</p>
        <div className="detail-actions"><button className="button button-ink" disabled={product.stock===0} onClick={e=>add(configuredProduct,e)}>Add to cart <Icon name="bag"/></button><button className="button" onClick={()=>toggleWish(product)}>{wished?"Saved to wishlist":"Add to wishlist"} <Icon name="heart"/></button></div>
        <button className="order-now" disabled={product.stock===0} onClick={()=>session ? setOrdering(true) : go("/login")}>Order now <Icon name="arrow"/></button>
        <div className="detail-note"><strong>Delivery:</strong> Nationwide dispatch with tracking updates.<br/><strong>Returns:</strong> Contact us within 7 days for eligible returns.<br/>Free shipping over PKR 5,000 · WhatsApp assistance</div>
      </div>
    </div>
    <AnimatePresence>{ordering&&<OrderForm items={[configuredProduct]} session={session} close={()=>setOrdering(false)}/>}</AnimatePresence>
  </main>;
}
function OrderForm({items,session,close,onComplete}) {
  const [status,setStatus]=useState("");
  const [sending,setSending]=useState(false);
  const total=items.reduce((sum,item)=>sum+Number(item.price)*(Number(item.quantity)||1),0);
  const submit=async e=>{e.preventDefault();if(!supabase||!session){setStatus("Please sign in before placing your order.");return;}setSending(true);setStatus("");const form=new FormData(e.currentTarget);const payment=form.get("payment");const {data:order,error}=await supabase.from("orders").insert({user_id:session.user.id,customer_name:form.get("name"),phone:form.get("phone"),address:form.get("address"),payment_method:payment,status:"pending_payment",total}).select().single();if(error){setStatus(error.message);setSending(false);return;}const orderItems=items.map(item=>({order_id:order.id,product_id:isUuid(item.id)?item.id:null,product_name:item.name + (item.selectedColor ? " — " + item.selectedColor : ""),unit_price:Number(item.price),quantity:Number(item.quantity)||1}));const {error:itemError}=await supabase.from("order_items").insert(orderItems);if(itemError){setStatus(`Your order could not be completed: ${itemError.message}`);setSending(false);return;}setStatus("Order placed — send your advance payment screenshot on WhatsApp for approval.");setSending(false);onComplete?.();};
  return <motion.div className="detail-layer" role="dialog" aria-modal="true" aria-label="Checkout" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.form className="checkout-panel" initial={{y:20}} animate={{y:0}} onSubmit={submit}><button type="button" className="icon-button detail-close" onClick={close} aria-label="Close checkout"><Icon name="close"/></button><p className="eyebrow">SECURE CHECKOUT</p><h2>Almost yours.</h2><div className="checkout-order-summary"><div><span>{items.length} {items.length===1?"item":"items"} in this order</span><strong>{money(total)}</strong></div>{items.map(item=><p key={item.id}>{item.name} <span>× {Number(item.quantity)||1}</span><strong>{money(Number(item.price)*(Number(item.quantity)||1))}</strong></p>)}</div><div className="checkout-fields"><label>Full name<input required name="name" autoComplete="name"/></label><label>WhatsApp number<input required name="phone" type="tel" autoComplete="tel"/></label><label>City<input required name="city" autoComplete="address-level2" placeholder="e.g. Lahore"/></label><label className="full-width">Complete delivery address<textarea required name="address" rows="3" autoComplete="street-address"/></label></div><fieldset><legend>Advance payment method</legend><label className="payment-option"><input defaultChecked type="radio" name="payment" value="easypaisa"/> EasyPaisa</label><label className="payment-option"><input type="radio" name="payment" value="jazzcash"/> JazzCash</label><label className="payment-option"><input type="radio" name="payment" value="bank_transfer"/> Meezan Bank debit card / transfer</label></fieldset><PaymentInstructions/><button className="button button-ink submit-order" disabled={sending}>{sending?"Saving order…":"Submit order"} <Icon name="arrow"/></button>{status&&<p className="form-status" role="status">{status}</p>}</motion.form></motion.div>;
}
function Cart({cart,go,session,clearCart}) { const [ordering,setOrdering]=useState(false);const total=cart.reduce((sum,item)=>sum+Number(item.price)*(Number(item.quantity)||1),0);return <main className="page-shell simple-page"><p className="eyebrow">SHOPPING BAG</p><h1>Your <em>bag.</em></h1>{cart.length?<div className="cart-checkout-layout"><div className="line-list">{cart.map(p=><div key={p.cartKey || p.id}><img src={p.image} alt=""/><span>{p.name}{p.selectedColor && <small>Colour: {p.selectedColor}</small>}<small>Quantity: {Number(p.quantity)||1}</small></span><strong>{money(Number(p.price)*(Number(p.quantity)||1))}</strong></div>)}</div><aside className="cart-summary"><p className="eyebrow">ORDER SUMMARY</p><div><span>Items ({cart.length})</span><strong>{money(total)}</strong></div><div><span>Delivery</span><strong>Calculated after order</strong></div><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="button button-ink" onClick={()=>session?setOrdering(true):go("/login")}>Proceed to checkout <Icon name="arrow"/></button><p>Advance payment is required. Your order stays pending until payment proof is approved.</p></aside></div>:<><p>Your bag is waiting for something special.</p><button className="button button-ink" onClick={()=>go("/shop")}>Shop now <Icon name="arrow"/></button></>}<AnimatePresence>{ordering&&<OrderForm items={cart} session={session} close={()=>setOrdering(false)} onComplete={clearCart}/>}</AnimatePresence></main> }function SimpleList({title,products,openProduct}) { return <main className="page-shell simple-page"><p className="eyebrow">TECHORA</p><h1>{title}</h1>{products.length?<div className="products-grid">{products.map((p,i)=><ProductCard key={p.id} product={p} index={i} openProduct={openProduct} add={()=>{}} wished toggleWish={()=>{}}/>)}</div>:<p>Nothing saved yet. Explore the collection to find your favourites.</p>}</main> }
function Orders({go}) { return <main className="page-shell simple-page"><p className="eyebrow">MY ACCOUNT</p><h1>Your <em>orders.</em></h1><div className="orders-empty"><Icon name="bag"/><h3>No orders yet</h3><p>When you place an order, its details will appear here.</p><button className="button button-ink" onClick={()=>go("/shop")}>Start shopping <Icon name="arrow"/></button></div></main> }
function Story({go}) { return <main className="page-shell story-page"><p className="eyebrow">OUR STORY</p><h1>Technology for a more <em>considered</em> life.</h1><p>Techora brings together useful, dependable technology with the personal service of a local Pakistani store.</p><button className="button button-ink" onClick={()=>go("/shop")}>Explore the edit <Icon name="arrow"/></button></main> }
function Footer({go}) { return <footer><div className="footer-main"><div><button className="wordmark" onClick={()=>go("/")}><img src={techoraLogo} alt="Techora Gadgets"/></button><p>Considered technology for modern life.</p></div><div><p className="footer-title">Explore</p><button onClick={()=>go("/shop")}>Shop</button><button onClick={()=>go("/story")}>Our story</button><button onClick={()=>go("/reviews")}>Reviews</button><button onClick={()=>go("/orders")}>My orders</button></div><div><p className="footer-title">Customer service</p><a href="https://wa.me/923229701332?text=Hi%20Techora%2C%20I%20need%20delivery%20information." target="_blank" rel="noreferrer">Delivery information</a><a href="mailto:techorapakistan@gmail.com">Email support</a></div><div><p className="footer-title">Follow along</p><div className="footer-socials"><a className="social-instagram" href="https://www.instagram.com/techorapakistan?stkn=MXNsb2diNmt5Yzh6ZA==" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" strokeWidth="1.7"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" strokeWidth="1.7"/><circle cx="17.4" cy="6.6" r="1" fill="currentColor"/></svg></a><a className="social-facebook" href="https://www.facebook.com/share/1fLZux37nz/" target="_blank" rel="noreferrer" aria-label="Facebook">f</a><a className="social-tiktok" href="https://www.tiktok.com/@techorapakistan" target="_blank" rel="noreferrer" aria-label="TikTok"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.5 3c.4 2.4 1.8 3.9 4.1 4.2v3.1c-1.5 0-2.8-.4-4.1-1.2v5.9a5.4 5.4 0 1 1-4.7-5.4v3.2a2.3 2.3 0 1 0 1.6 2.2V3h3.1Z" fill="currentColor"/></svg></a><a className="social-whatsapp" href="https://wa.me/923229701332" target="_blank" rel="noreferrer" aria-label="WhatsApp"><Icon name="whatsapp"/></a></div></div></div><div className="footer-bottom"><span>© 2026 Techora Pakistan</span><div className="footer-payments"><img src={easypaisaLogo} alt="EasyPaisa"/><img src={jazzcashLogo} alt="JazzCash"/><span className="visa">VISA</span></div></div></footer> }
